export default function DisclaimerBanner() {
  return (
    <div style={{
      background: 'rgba(251, 191, 36, 0.08)',
      border: '1px solid rgba(251, 191, 36, 0.3)',
      borderLeft: '4px solid var(--accent-amber)',
      borderRadius: 'var(--radius-sm)',
      padding: '12px 16px',
      marginBottom: '2rem',
      color: '#d4a72c',
      fontSize: '0.85rem',
      lineHeight: 1.5,
    }}>
      <strong>Educational purposes only.</strong> Stock suggestions are generated by AI and do not
      constitute financial advice. Always consult a licensed financial advisor before making
      investment decisions.
    </div>
  );
}
